import * as React from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useQuery } from '@apollo/client'

import UserInfo from '../../components/userInfo'
import RepositoriesSection from '../../components/githubRepositoriesSection'
import prisma from '../../lib/prisma'
import { GET_USER_INFO } from '../../lib/graphql/queries'

import type { GetServerSideProps, NextPage } from 'next'

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const user = await prisma.user.findUnique({
    where: {
      username: `${ctx.query.username}`,
    },
  })

  if (user) {
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
    }
  }

  return {
    props: {},
  }
}

const Home: NextPage = () => {
  const router = useRouter()
  const [activeTab, setActiveTab] = React.useState<'repos' | 'starred'>('repos')
  const { data, loading, fetchMore } = useQuery(GET_USER_INFO, {
    variables: {
      login: router.query.username,
      afterRepos: null,
      beforeRepos: null,
      afterStarredRepos: null,
      beforeStarredRepos: null,
    },
  })

  return (
    <>
      <Head>
        <title>My Profile | Homepage</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='container mx-auto pt-16 flex'>
        {!data?.user || loading ? (
          <p>loading..</p>
        ) : (
          <div className='flex flex-col lg:flex-row w-full gap-2'>
            <UserInfo
              avatarUrl={data.user.avatarUrl}
              bio={data.user.bio}
              company={data.user.company}
              email={data.user.email}
              followers={data.user.followers.totalCount}
              following={data.user.following.totalCount}
              username={data.user.login}
              name={data.user.name}
            />
            <div className='w-full lg:w-3/5 xl:w-3/4'>
              <div className='w-full px-6 border-b py-3 flex space-x-4 mb-6'>
                <button
                  type='button'
                  onClick={() => setActiveTab('repos')}
                  className={`${
                    activeTab === 'repos'
                      ? 'text-gray-400 border-t-2 border-gray-400 text-lg'
                      : 'hover:text-gray-400'
                  }`}
                >
                  Repositories
                </button>
                <button
                  type='button'
                  onClick={() => setActiveTab('starred')}
                  className={`${
                    activeTab === 'starred'
                      ? 'text-gray-400 border-t-2 border-gray-400 text-lg'
                      : 'hover:text-gray-400'
                  }`}
                >
                  Starred Repositories
                </button>
              </div>
              {activeTab === 'repos' ? (
                <RepositoriesSection
                  repositories={data.user.repositories.edges}
                  pageInfo={data.user.repositories.pageInfo}
                  fetchMore={fetchMore}
                  tab={activeTab}
                />
              ) : (
                <RepositoriesSection
                  repositories={data.user.starredRepositories.edges}
                  pageInfo={data.user.starredRepositories.pageInfo}
                  fetchMore={fetchMore}
                  tab={activeTab}
                />
              )}
            </div>
          </div>
        )}
      </section>
    </>
  )
}

export default Home
